In [5]:
import numpy as np

In [44]:
# 1.4.43.

m1 = np.matrix([[1, -1, -1], [-1, 2, 1], [-1, 1, 2]], dtype=np.float64)
print(np.linalg.inv(m1))


# 1.4.45

m2 = np.matrix([[1, 2, -2, 4], [2, 6, 1, 0], [3, 0, 1, 2], [-1, 4, 5, -4]], dtype=np.float64)
print(np.linalg.inv(m2))

[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[-0.31666667  0.25        0.2        -0.21666667]
 [ 0.075       0.125      -0.1         0.025     ]
 [ 0.18333333 -0.25        0.2         0.28333333]
 [ 0.38333333 -0.25        0.1         0.18333333]]


In [43]:
# 5

m3 = np.matrix([[-1, 2], [0, 5], [3, -1]], dtype=np.float64)
m4 = np.matrix([[2, -3], [1, 4]], dtype=np.float64)
print(m3 @ np.linalg.inv(m4))

[[-0.54545455  0.09090909]
 [-0.45454545  0.90909091]
 [ 1.18181818  0.63636364]]


In [52]:
# 2.2.13

m5 = np.matrix([[3, -5, 2, -4], [-3, 4, -5, 3], [-5, 7, -7, 5], [8, -8, 5, -6]], dtype=np.float64)
m6 = np.matrix([[0], [-2], [-2], [-5]], dtype=np.float64)
print(m5 @ m6)


# 2.2.14

m7 = np.matrix([[6, -5, 4, 7], [5, -8, 5, 8], [9, -8, 5, 10], [3, 2, 2, 2]], dtype=np.float64)
m8 = np.matrix([[28], [36], [42], [2]], dtype=np.float64)
print(m7 @ m8)

[[ 26.]
 [-13.]
 [-25.]
 [ 36.]]
[[170.]
 [ 78.]
 [194.]
 [244.]]
