<center>
<img src="dls.jpg" width="500" height="500">

<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ</b></h3>
<h3 style="text-align: center;"><b>Базовый поток. Осень 2020</b></h3>

<h1 style="text-align: center;"><b>Неделя 2. Библиотека NumPy</b></h1>

***Мы могли писать такой код и ни о чем не задумываться.***

In [2]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

CPU times: total: 1.52 s
Wall time: 1.55 s


***Или такой...***

In [3]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += i
    return ans

arr = range(10**7)

print(summ(arr))

49999995000000
CPU times: total: 766 ms
Wall time: 784 ms


# Библиотека Numpy.
- ***``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.***


- ***Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.***

In [4]:
!where python

c:\Users\Shumann\AppData\Local\Programs\Python\Python311\python.exe


In [ ]:
# !conda install numpy
# !pip3 install numpy

In [1]:
import numpy as np

## 1. Одномерные массивы

In [6]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), type(a))

<class 'numpy.ndarray'> <class 'list'>


***Если типы разные, то идет неявный каст к одному.***

In [7]:
a = [1, 2, 'a']
b = np.array(a)
print("Для list:", type(a[0]),
      "\nДля np.array:", type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [8]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [9]:
type(d)

numpy.ndarray

***Можем посмотреть на все методы класса ``ndarray``.***

In [10]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',

***Например узнаем размер массива.***

In [11]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [14]:
arr.nbytes


20

***Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.***

In [15]:
np.lookfor('mean value of array') 

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.isrealobj
    Return True if x is a not complex type or an array of complex numbers.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Retur

***Далее можно почитать документацию про контретную функцию.***

In [16]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x0000019C8F9B3990>
File:            c:\users\shumann\appdata\local\programs\python\python311\lib\site-packages\numpy\ma\core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average : Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of th

In [17]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

***Посмотрим на количественные характеристики ``ndarray``.***

In [22]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [19]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


***Индексы.***

In [20]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

***Последний элемент.***

In [ ]:
a[-1]

***Можем изменять объекты массива.***

In [ ]:
a[2] = -1
a

***``ndarray`` можно использовать в циклах. Но при этом теряется главное преимущество `Numpy` -- быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.***

In [ ]:
for i in a:
    print(i)

**Задача 1:** Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер:

In [ ]:
# решение



## Создание массивов.

In [23]:
a = np.zeros(7) # массив из нулей
b = np.ones(7, dtype=np.int16) # массив из единиц
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


***Часто нужно создать нулевой массив такой же как другой.***

In [24]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [25]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

***Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг -- целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.***

In [26]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


***Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.***

In [ ]:
a = np.linspace(1, 15, 2)
b = np.linspace(5, 12, 10)
print(a)
print(b)

**Задача 2:** создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [ ]:
# решение




***Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.***

In [ ]:
b = np.logspace(0, 3, 12)
print(b)

# 2. Операции над одномерными массивами.

***Все арифметические операции производятся поэлементно.***

In [ ]:
print(a)
print(b)

In [ ]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

***Один из операндов может быть скаляром, а не массивом.***

In [ ]:
print(5*a)
print(10 + b)

***Если типы элементов разные, то идет каст к большему.***

In [ ]:
print(a + np.arange(11, dtype='int16'))
print(type(a[0]))

***В ``Numpy`` есть элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (``ufunc``).***

In [ ]:
type(np.cos)

In [ ]:
np.cos(a)

In [ ]:
np.log(b)

***Логические операции также производятся поэлементно.***

In [ ]:
print(a > b)
print(a == b)
print(a >= 10)

***Кванторы ``всеобщности`` и ``существования``.***
$$\forall$$
$$\exists$$

In [ ]:
c = np.arange(0., 20)
print(type(c[0]))

In [ ]:
np.any(c), np.all(c)

***Inplace операции.***

In [ ]:
c += np.sin(4)
print(c)

***Inplace операции возможны только для операндов одинакового типа.***

In [ ]:
c *= 2
print(c)

In [ ]:
b = np.arange(1., 21, 1)

d = (b + c)
d /= b
print(d)

***При делении ``ndarray`` на нули, исключения не бросается.***

In [ ]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

***Могут понадобится константы.***

In [ ]:
print(np.e, np.pi)

In [ ]:
print(b)
print(b.cumsum())

***Посмотрим на сортировку numpy-массивов.***

In [ ]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [ ]:
print(np.sort(a))
print(a)

***Теперь попробуем как метод.***

In [ ]:
a.sort()
print(a)

In [ ]:
b = np.ones(5)
b

***Объединим массивы.***

In [ ]:
c = np.hstack((a, b, 5*b))
c

***Расщепление массива.***

In [ ]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(x1)
print(x2)
print(x3)
print(x4)

***Функции ``append`` ``delete`` ``insert`` не Inplace функции.***

In [ ]:
print(np.delete(a, [2, 4, 1]))
print(a)

In [ ]:
np.insert(a, 2, [-1, -1])

In [ ]:
np.append(a, [2.2, 2.1])

## Индексирование массивов и срезы

***Массив в обратном порядоке.***

In [ ]:
a[::-1]

***Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.***

In [ ]:
print(a)

In [ ]:
a[2:5]

In [ ]:
b = a[0:6] # копия не создается
b[1] = -1000
print(a)

***Диапозоны с шагами.***

In [ ]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

***Чтобы скопировать и данные массива, нужно использовать метод ``copy``.***

In [ ]:
b = a.copy()
b[2] = -4
print(b)
print(a)

In [ ]:
print(a[[5,3,1]]) # массив индексов

**Задание 3:**  
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что сумма по всем точкам равна 100.

In [ ]:
# решение



# 3. Двумерные массивы

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

In [ ]:
a.ndim, a.shape, len(a), a.size

***Обращение по индексу.***

In [ ]:
a[1][1], a[1,1]

***Атрибуту ``shape`` можно присвоить новое значение -- кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.***

In [ ]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)

In [ ]:
print(b.ravel()) # стягивание в одномерный массив

In [ ]:
a = np.ones((3, 3)) # подать tuple
print(a)

In [ ]:
b = np.zeros((3, 4))
print(b)

In [ ]:
c = np.eye(3)
print(c)

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

***Задание 4:***
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [ ]:
# решение




***Умножение матриц.***

In [ ]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

In [ ]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) 

***Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$***

In [ ]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)
print(u)
print(v)

In [2]:
x, y = np.meshgrid(u, v)
print(x, '\n')
print(y)

NameError: name 'np' is not defined

In [ ]:
print(x.reshape(6)) #тоже самое что и shape

***Задание 5:***
- Отобразить матрицу, в которой вычеркивается **(x, y)**, если **y** делится на **x**.

<center>
<img src="mat.png" width="500" height="500">

In [ ]:
is_prime = np.ones(100, dtype=bool)

In [ ]:
is_prime[:2] = False

In [ ]:
N_max = int(np.sqrt(len(is_prime)))
for i in range(2, N_max):
    is_prime[2*i::i] = False # начинаем с 2i с шагом i
    
print(is_prime)
print(is_prime[17])
print(is_prime[90])

***Маски.***

In [ ]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

***След (trace) - сумма диагональных элементов.***

In [ ]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

# 4. Тензоры (многомерные массивы)

In [ ]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

In [ ]:
X.shape, len(X), X.size, X.ndim

***Посмотрим на суммы по разным осям.***

In [ ]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# суммируем сразу по двум осям, то есть для фиксированной i 
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

# 5. Линейная алгебра

In [ ]:
a = np.array([[2, 1], [2, 3]])
print(a)

***Определитель.***

In [ ]:
np.linalg.det(a)

***Нахождениия обратной.***

In [ ]:
b = np.linalg.inv(a)
print(b)

In [ ]:
print(a.dot(b))
print(b.dot(a))

***Решение НЛУ.***
$$ A \cdot x = v $$

In [ ]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

***Найдем собственные вектора матрицы A.***
$$ A \cdot x = \lambda \cdot x $$

In [ ]:
l, u = np.linalg.eig(a)
print(l)
print(u)

***Собственные значения матриц A и A.T совпадают.***

In [ ]:
l, u = np.linalg.eig(a.T)
print(l)
print(u)

In [ ]:
l, u = np.linalg.eig(np.eye(3))
print(l)
print(u)

***Производительность.***

In [ ]:
%%time

sum_value = np.sum(np.arange(10**7))
print(sum_value)

In [ ]:
%%time
arr = 5*np.arange(10**7)

# Полезные ссылки

[DLS прошлый год](https://stepik.org/course/65388/promo)

[Введение в Анализ Данных](https://mipt-stats.gitlab.io/jekyll/update/2020/02/01/ad.html)

[GitHub NumPy](https://github.com/numpy/numpy)

[mlcource.ai](https://mlcourse.ai)